spring.application.name=securitydemo
spring.security.user.password = demo@123
spring.security.user.name = admin

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test

spring.app.jwtSecret=mySecretKey123912738asdfghjlkjhgfdsasdfghjaghdjhsjdgfwiwyehewhehe7hdbhebhdasdfghjkjhgfd
spring.app.jwtExpirationMS=3000000

logging.level.org.springframeworkframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframeworkframework.security=DEBUG
logging.level.com.example.securitydemo=DEBUG